### ISSUE TITLE
KeyError during loading the model

### ISSUE THREAD

**Issue by mzshuo** [shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome#11]
Hi,

Thanks for your great job. 
I meet the following problem when loading the model downloaded from this repo.

load checkpoint data/pretrained_model/faster_rcnn_res101_vg.pth
Traceback (most recent call last):
  File "generate_tsv.py", line 455, in <module>
    generate_tsv(args.outfile, image_ids, args)
  File "generate_tsv.py", line 428, in generate_tsv
    classes, fasterRCNN = load_model(args)
  File "generate_tsv.py", line 402, in load_model
    fasterRCNN.load_state_dict(checkpoint['model'])
KeyError: 'model'

Could you please offer some advice? Thanks in advance.

**Comment by mzshuo** [comment]
Solved. The model downloaded from Google Drive is right. Previous model was downloaded from DropBox or VT Server link.

**Comment by whoopee** [comment]
@shuorr Hi! 
I have the same problem.

Please let me know where you find the link to the correct model on Google Drive? 
I could not find the correct one. 
Models from DropBox and VT Server have noncorrect layer names... 


UPDATE: I have found it. The link is in the table! And it is pretrained on VG dataset.

**Comment by Longtime1994** [comment]
@shuorr Hi!
I have the same problem.
When I load checkpoint data/pretrained_model/faster_rcnn_res101_vg.pth I met this issue '' RuntimeError('Attempting to deserialize object on a CUDA '''

**Comment by mzshuo** [comment]
> @shuorr Hi! I have the same problem. When I load checkpoint data/pretrained_model/faster_rcnn_res101_vg.pth I met this issue '' RuntimeError('Attempting to deserialize object on a CUDA '''

@Longtime1994 Hi!
Maybe your cuda version is not compatible with pytorch requirement?  I'm not sure. I googled it. Hope it is helpful. 😄
